// Minimal config with no real API keys — all services disabled
export const config = {
  anthropicApiKey: "",
  replicateApiToken: "",
  openaiApiKey: "",
  supabaseUrl: "",
  supabaseServiceKey: "",
  port: 3001,
  nodeEnv: "test",
  frontendUrl: "http://localhost:8081",
  posthogApiKey: "",
  posthogHost: "",
  sentryDsn: "",
  revenuecatWebhookSecret: "test-secret-123",
  get hasAnthropic() { return this.anthropicApiKey.length > 0; },
  get hasReplicate() { return this.replicateApiToken.length > 0; },
  get hasOpenAI() { return this.openaiApiKey.length > 0; },
  get hasImageGen() { return this.hasReplicate || this.hasOpenAI; },
  get hasVision() { return this.hasAnthropic || this.hasOpenAI; },
  get hasSupabase() { return this.supabaseUrl.length > 0 && this.supabaseServiceKey.length > 0; },
  get hasPostHog() { return this.posthogApiKey.length > 0; },
  get hasSentry() { return this.sentryDsn.length > 0; },
  get hasRevenueCat() { return this.revenuecatWebhookSecret.length > 0; },
};
